name: flutter_mvvm_riverpod_boilerplate
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  easy_localization: ^3.0.7+1
  auto_route: ^9.3.0+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.10
  build_runner: ^2.4.14
  retrofit_generator: ^9.1.7
  json_serializable: ^6.9.3
  freezed: ^2.5.8
  auto_route_generator: ^9.3.1
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/svg/
    - lib/assets/icons/other/
    - lib/assets/images/svg/
    - lib/assets/images/other/
    - lib/assets/google_fonts/
    - lib/core/i18n/langs/
